Save enriched ads to a Pickle file, create index from that file
JobtechSwe/elastic-importers pull request #61
Opened 2021-03-24 08:59 UTC by oskardrenske-ith

Save enriched ads to a Pickle file so that they can be imported from that file in any Elastic

2021-03-24 09:06 UTC, halge approved these changes

2021-03-24 16:04 UTC, halge requested changes

2021-03-24 16:04 UTC, halge commented on importers/platsannons/main.py
> +        save_enriched_ads_to_file(enriched_ads_to_save)
enriched_ads_to_save: will it be accessible from another func? it is not global.

2021-03-24 16:04 UTC, halge commented on importers/settings.py
> +SAVE_ENRICHED_ADS = False
use os.getenv with default.

2021-03-25 06:21 UTC, oskardrenske-ith commented on importers/platsannons/main.py
> +        save_enriched_ads_to_file(enriched_ads_to_save)
works without 'global' keyword, but I added it for readability

2021-03-25 06:24 UTC, oskardrenske-ith commented on importers/platsannons/main.py
> +        save_enriched_ads_to_file(enriched_ads_to_save)
yes it works. I added 'global' keyword where ads are saved to 'enriched_ads_to_save' list for readability

2021-03-25 09:01 UTC, halge approved these changes

2021-03-25 14:51 UTC, lina1101 approved these changes

2021-03-25 14:53 UTC, merged