Update date skill and occupation
JobtechSwe/elastic-importers pull request #62
Opened 2021-04-08 07:33 UTC by lina1101

2021-04-08 07:41 UTC, halge requested changes

2021-04-08 07:41 UTC, halge commented on importers/platsannons/converter.py
> +        elif old_term_concept_id == internal_content.get("taxonomy/id"):
should we add else with some informative log?

2021-04-08 07:51 UTC, lina1101 commented on importers/platsannons/converter.py
> +        elif old_term_concept_id == internal_content.get("taxonomy/id"):
I do not think it is useful

2021-04-13 10:12 UTC, oskardrenske-ith approved these changes

2021-04-13 10:30 UTC, halge approved these changes

2021-04-13 10:32 UTC, merged