Takes care of the case: changed occupation name while same concept_id
JobtechSwe/elastic-importers pull request #68
Opened 2021-06-08 08:38 UTC by erik-gbg

2021-06-08 09:06 UTC, erik-gbg commented
Hmm, I should probably add some unit test for this...

2021-06-08 09:29 UTC, oskardrenske-ith approved these changes

2021-06-08 09:44 UTC, halge requested changes
add unit test

2021-06-08 12:40 UTC, lina1101 approved these changes

2021-06-09 12:32 UTC, halge approved these changes

2021-06-11 07:53 UTC, merged