Add municipality lost parent
JobtechSwe/elastic-importers pull request #74
Opened 2021-07-07 13:15 UTC by lina1101

2021-07-07 13:45 UTC, halge approved these changes

2021-07-07 14:36 UTC, erik-gbg reviewed
There will be some merging conflicts with the one I committed. But we'll sort it out.

2021-07-07 15:31 UTC, erik-gbg requested changes
1. Fix so that unit tests don't crash
2. Then make a quick fix so that unit tests do not fail (hot tip = del keyword)
3. Finally add a TODO reminding us to fix these unit tests properly in the future

2021-07-07 16:27 UTC, halge requested changes
unit tests

2021-07-08 06:40 UTC, oskardrenske-ith requested changes
unit test for function importers/taxonomy/converter.py:convert_municipality_value() fails

2021-07-08 07:44 UTC, erik-gbg approved these changes

2021-07-08 07:52 UTC, lina1101 commented on tests/unit_tests/test_taxonomy_converter.py
> +    del converted['parent']
I think you should add parent data to the municipality to test it together instead of deleting parent data. Otherwise, parent data could never be tested.

2021-07-08 07:53 UTC, oskardrenske-ith commented on importers/taxonomy/queries.py
> +  concepts(type: "occupation-name", include_deprecated: true, version: "2") {
can repeated version string be a variable instead of written in each query?

2021-07-08 08:26 UTC, halge commented on importers/taxonomy/queries.py
> +  concepts(type: "occupation-name", include_deprecated: true, version: "2") {
already merge from develop

2021-07-08 09:25 UTC, erik-gbg commented on tests/unit_tests/test_taxonomy_converter.py
> +    del converted['parent']
I have done what I said above, which is what is needed for now:
1. Fix so that unit tests don't crash
2. Then make a quick fix so that unit tests do not fail (hot tip = del keyword)
3. Finally add a TODO reminding us to fix these unit tests properly in the future

If you want to do tests for parent data, you are welcome. But it's not needed for now.

2021-07-08 09:39 UTC, erik-gbg requested changes
Now unit tests break again

2021-07-08 10:12 UTC, halge approved these changes

2021-07-08 10:15 UTC, erik-gbg approved these changes

2021-07-08 10:18 UTC, merged