RC 1.5.1
JobtechSwe/elastic-importers pull request #76
Opened 2021-07-08 13:43 UTC by halge

2021-07-08 13:49 UTC, oskardrenske-ith commented on CHANGELOG.md
>  # 1.5.0
Add 1.5.1 and changes

2021-07-08 13:50 UTC, lina1101 approved these changes

2021-07-08 13:53 UTC, oskardrenske-ith requested changes
Update changelog.md with version 1.5.1 and info on changes

2021-07-08 14:43 UTC, erik-gbg reviewed
What Oskar said above, and that should be the only thing

2021-07-09 09:15 UTC, erik-gbg approved these changes

2021-07-09 09:16 UTC, oskardrenske-ith approved these changes

2021-07-09 09:17 UTC, erik-gbg approved these changes

2021-09-02 12:21 UTC, lina1101 approved these changes

2021-09-20 13:01 UTC, halge reviewed
ok

2021-09-30 16:40 UTC, merged